{{- with .Values.wopibridge }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wopiserver.fullname" $ }}-{{ .name }}-secret
  labels:
    {{- include "wopibridge.labels" $ | nindent 4 }}
type: Opaque
data:
  {{ if .secrets.wbsecret }}
  wbsecret: "{{ .secrets.wbsecret | b64enc }}"
  {{ else }}
  wbsecret: "{{ randAlphaNum 24 | b64enc }}"
  {{ end }}
  {{ if .secrets.codimd_apikey }}
  codimd_apikey: "{{ .secrets.codimd_apikey | b64enc }}"
  {{ else }}
  codimd_apikey: "{{ randAlphaNum 24 | b64enc }}"
  {{ end }}
{{- end }}
{{- end }}
