apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wopiserver.fullname" . }}
  labels:
    {{- include "wopiserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wopiserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wopiserver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8880
              protocol: TCP
          volumeMounts:
            - name: {{ include "wopiserver.fullname" . }}-confdir
              mountPath: /etc/wopi/wopiserver.conf
              subPath: wopiserver.conf
            - name: {{ include "wopiserver.fullname" . }}-confdir
              mountPath: /etc/wopi/wopisecret
              subPath: wopisecret
            - name: {{ include "wopiserver.fullname" . }}-confdir
              mountPath: /etc/wopi/iopsecret
              subPath: iopsecret
            - name: {{ include "wopiserver.fullname" . }}-secret
              mountPath: /var/run/secrets
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      volumes:
        - name: {{ include "wopiserver.fullname" . }}-confdir
          projected:
            sources:
              - configMap:
                  name: {{ template "wopiserver.fullname" . }}-config
              - secret:
                  name: {{ template "wopiserver.fullname" . }}-secrets
        - name: {{ .name }}-secret
          secret:
            secretName: {{ include "wopiserver.fullname" $ }}-secret
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
