apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wopiserver.fullname" . }}
  labels:
    {{- include "wopiserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wopiserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wopiserver.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
          fsGroup: {{ $.Values.securityContext.fsGroup }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ $.Values.securityContext.runAsUser }}
            runAsGroup: {{ $.Values.securityContext.runAsGroup }}
            readOnlyRootFilesystem: true
          resources: {{ toYaml $.Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 8880
              protocol: TCP
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: log-volume
              mountPath: /var/log/wopi/
            - name: recovery-volume
              mountPath: /var/spool/wopirecovery/
            # config
            - name: config
              mountPath: /etc/wopi/wopiserver.conf
              subPath: wopiserver.conf
            # secrets
            - name: secrets
              mountPath: /var/run/secrets/wopisecret
              subPath: wopisecret
            - name: {{ include "wopiserver.fullname" . }}-confdir
              mountPath: /etc/wopi/iopsecret
              subPath: iopsecret
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range (default .Values.image.pullSecrets) }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: log-volume
          emptyDir: {}
        - name: recovery-volume
          emptyDir: {}
        - name: config
          configMap:
            name: {{ template "wopiserver.fullname" . }}-config
        - name: secrets
          secret:
            {{ if .Values.secretsRef }}
            secretName: {{ .Values.secretsRef }}
            {{ else }}
            secretName: {{ template "wopiserver.fullname" . }}-secrets
            {{ end }}
