apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wopiserver.fullname" . }}-secrets
  labels:
    {{- include "wopiserver.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.config.wopisecret }}
  wopisecret: "{{ .Values.config.wopisecret | b64enc }}"
  {{ else }}
  wopisecret: "{{ randAlphaNum 24 | b64enc }}"
  {{ end }}
  {{ if .Values.config.iopsecret }}
  iopsecret: "{{ .Values.config.iopsecret | b64enc }}"
  {{ else }}
  iopsecret: "{{ randAlphaNum 24 | b64enc }}"
  {{ end }}
