{{ if not .Values.secretsRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wopiserver.fullname" . }}-secrets
  labels:
    {{- include "wopiserver.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.secrets.wopiSecret }}
  wopisecret: "{{ .Values.secrets.wopiSecret | b64enc }}"
  {{ else }}
  wopisecret: "{{ randAlphaNum 24 | b64enc }}"
  {{ end }}
{{ end }}
