{{- if and .Values.configFiles (not .Values.cfgmapName) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "revad.fullname" . }}-config
  labels:
    {{- include "revad.labels" . | nindent 4 }}
data:
{{- range $filename, $fileContents := .Values.configFiles }}
  {{ $filename }}: |-
{{ tpl $fileContents $ | indent 4 }}
{{- end }}
{{- end }}
