{{- range $configMapName, $configMap := .Values.configFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "revad.fullname" $ }}-{{ $configMapName }}-config
  labels:
    {{- include "revad.labels" $ | nindent 4 }}
data:
{{- range $filename, $fileContents := $configMap }}
  {{ $filename }}: |-
{{ $fileContents | indent 4 }}
{{- end }}
---
{{- end }}
