{{ if not .Values.secretsRef }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "idp.fullname" . }}-secrets
  labels:
    {{- include "idp.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  {{ if .Values.secrets.machineAuthApiKey }}
  machineAuthApiKey: "{{ .Values.secrets.machineAuthApiKey | b64enc }}"
  {{ else }}
  machineAuthApiKey: "{{ randAlphaNum 50 | b64enc }}"
  {{ end }}
  {{ if .Values.secrets.encryptionKey }}
  encryption.key: "{{ .Values.secrets.encryptionKey | b64enc }}"
  {{ else }}
  encryption.key: "{{ randBytes 32 }}"
  {{ end }}
  {{ if .Values.secrets.privateKey }}
  private-key.pem: "{{ $.Files.Get .Values.secrets.privateKey | b64enc }}"
  {{ else }}
  private-key.pem: "{{ genPrivateKey rsa | b64enc }}"
  {{ end }}
{{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idp.fullname" . }}-config-secret
  labels:
    {{- include "idp.labels" . | nindent 4 }}
data:
  ocis.yaml: |
    idp:
      iss: {{ include "idp.url" . }}
      identity_manager: cs3
      signing_private_key_files:
        - /etc/ocis/idp/private-key.pem
      encrypt_secret_file: /etc/ocis/idp/encryption.key
      access_token_duration_seconds: {{ .Values.idp.accessTokenValidity }}
      id_token_duration_seconds: {{ .Values.idp.idTokenValidity }}
      refresh_token_duration_seconds: {{ .Values.idp.refreshTokenValidity }}
      {{- if .Values.idp.clients }}
      clients:
      {{ toYaml .Values.idp.clients | indent 2 }}
      {{ else }}
      clients: []
      {{- end }}
    http: 
      addr: 0.0.0.0:{{ .Values.service.port }}
    reva:
      address: {{ .Values.cs3.gateway }}
    log:
      level: "{{ .Values.log.level }}"
      pretty: {{ .Values.log.pretty }}
      color: {{ .Values.log.color }}
    auth_bearer:
      auth_providers:
        oidc:
          insecure: false
    proxy:
      insecure_backends: false
